### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectedRemote' of undefined

### ISSUE THREAD

**Issue by rtweeks** [rtweeks/casefile#4]
[Enter steps to reproduce:]

1. Open Casefile (*Casefile: Open* command in Command Palette).
2. Open the Casefile Sharing tab (*Casefile: Share* command in Command Palette).
3. *Fetch Shared* when there is no branch in the selected Git remote.  This might also require that there is no persisted state for the `CasefileSharingModel`.

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [casefile](https://github.com/rtweeks/casefile) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'selectedRemote' of undefined

```
At /Users/richardt/github/casefile/lib/presentation/CasefileSharing.js:50

TypeError: Cannot read property 'selectedRemote' of undefined
    at ToolPanel.render (/Users/richardt/github/casefile/lib/presentation/CasefileSharing.js:50:44)
    at updateSync (/packages/teletype/node_modules/etch/lib/component-helpers.js:107:34)
    at Object.update (/packages/teletype/node_modules/etch/lib/component-helpers.js:62:5)
    at ToolPanel.update (/Users/richardt/github/casefile/lib/presentation/CasefileSharing.js:125:17)
    at updateComponent (/packages/teletype/node_modules/etch/lib/patch.js:52:13)
    at patch (/packages/teletype/node_modules/etch/lib/patch.js:16:19)
    at updateSync (/packages/teletype/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/teletype/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/packages/teletype/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
     -1:00.6.0 command-palette:toggle (div.tool-panel.tree-view)
     -0:59.1.0 core:confirm (input.hidden-input)
     -0:58.7.0 casefile:open (div.tool-panel.tree-view)
     -0:53.7.0 casefile:share (div.bookmarks)
```

### Non-Core Packages

```
atom-gdiff 0.0.0 
atom-shell-commands 1.5.0 
atom-xsltransform 1.0.0 
autocomplete-python 1.14.0 
autocomplete-python-jedi 1.10.3-0 
byebug-breakpoints 0.2.5 
casefile 1.3.0 
character-table 0.4.3 
chrome-color-picker 0.8.0 
clipboard-plus 0.5.1 
graphviz-preview-plus 1.5.9 
language-asn1 0.3.0 
language-dot 1.7.0 
language-haml 0.32.1 
language-haskell 1.18.1 
language-latex 1.2.0 
language-pgsql 0.2.3 
language-powershell 5.0.0 
language-TSQL-2012 0.3.0 
language-vbscript 0.9.0 
latex 0.50.2 
latexer 0.3.0 
latextools 0.8.5 
pdf-view 0.71.0 
python-jedi 0.3.8 
rails-transporter 1.7.1 
random 1.4.1 
teletype 0.13.4 
unicode-normalizer 0.2.1 
unique-code 0.3.1 
```

**Comment by rtweeks** [comment]
Fixed by fb8d3a4fb01143804379a00846220813d1004765
